[api]
api_url="https://virtserver.swaggerhub.com/wcd_de_lab/top10/1.0.0/add"

[s3]
bucket='python-lambda-project'
folder='input'

[db]
host='cgo3thhmgh0u.us-east-1.rds.amazonaws.com'
port=3306
database='database-2'
schema='superstore'

[run]
py_script="run.py"